### ISSUE TITLE
Please remove explicit EUMM 6.30 requirement

### ISSUE THREAD

**Issue by cpansprout** [madsen/io-html#2]
More specifically, when you next release this, please make sure you are using Dist::Zilla 5.020 or higher, which does not specify a minimum version for ExtUtils::MakeMaker.  (If I just comment out the version number, the thing runs just fine with EUMM 6.17.)

No hurry. :-)

**Comment by madsen** [comment]
Version 1.004 was released with the current Dist::Zilla.  I didn't hurry. :-)
