### ISSUE TITLE
Hi, Is the perl-IO-HTML component being maintained?

### ISSUE THREAD

**Issue by FWT-Henry** [madsen/io-html#3]
Hi,
Is the perl-IO-HTML component being maintained? It seems like it hasn't been updated for a long time.
^_^

**Comment by FWT-Henry** [comment]
Hi,
can you answer my question, is the perl-IO-HTML component being maintained?and is there a new version to be updated?tks

**Comment by madsen** [comment]
It's maintained in the sense I intend to fix bugs, but none have been reported in the past 5 years.  I did let the last trial release go on far too long before releasing a stable version, but 1.004 is out now; thanks for prodding me.  It's just 1.003 with some minor documentation improvements.

I don't expect to add any new features, so the next release (if any) will probably not be until somebody reports a bug.
